version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8081:8081"
    environment:
      - "DATABASE_USER=postgres"
    command: "bundle exec rails server -b 0.0.0.0 -p 8081"
